import Config
# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :hub_ledger, HubLedgerWeb.Endpoint,
  url: [host: System.get_env("HUBLEDGER_HOST"), scheme: "https", port: 443],
  http: [
    port: String.to_integer(System.get_env("HUBLEDGER_PORT") || "4001"),
    transport_options: [socket_opts: [:inet6]]
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

database_url =
  System.get_env("HUBLEDGER_DATABASE_URL") ||
    raise """
    environment variable HUBLEDGER_DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

secret_key_base =
  System.get_env("HUBLEDGER_SECRET_KEY_BASE") ||
    raise """
    environment variable HUBLEDGER_SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :hub_ledger, HubLedgerWeb.Endpoint, secret_key_base: secret_key_base

config :hub_ledger, HubLedger.Repo,
  url: database_url,
  pool_size: String.to_integer(System.get_env("HUBLEDGER_POOL_SIZE") || "10")
