{application,ex_machina,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"A factory library by the creators of FactoryGirl"},
              {modules,['Elixir.ExMachina','Elixir.ExMachina.Ecto',
                        'Elixir.ExMachina.EctoStrategy',
                        'Elixir.ExMachina.Sequence',
                        'Elixir.ExMachina.Strategy',
                        'Elixir.ExMachina.UndefinedFactoryError']},
              {registered,[]},
              {vsn,"2.4.0"},
              {mod,{'Elixir.ExMachina',[]}}]}.
