{application,sendgrid,
             [{applications,[kernel,stdlib,elixir,logger,jason,tesla]},
              {description,"A wrapper for SendGrid's API to create composable emails.\n"},
              {modules,['Elixir.Jason.Encoder.SendGrid.Contacts.Recipient',
                        'Elixir.Jason.Encoder.SendGrid.Email',
                        'Elixir.Jason.Encoder.SendGrid.Personalization',
                        'Elixir.SendGrid','Elixir.SendGrid.Contacts.Lists',
                        'Elixir.SendGrid.Contacts.Recipient',
                        'Elixir.SendGrid.Contacts.Recipients',
                        'Elixir.SendGrid.Email','Elixir.SendGrid.Mail',
                        'Elixir.SendGrid.Personalization',
                        'Elixir.SendGrid.Response']},
              {registered,[]},
              {vsn,"2.0.0"}]}.
