import Config
# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.

config :hub_crm, HubCrmWeb.Endpoint,
  url: [host: System.get_env("HUBCRM_HOST"), scheme: "https", port: 443],
  http: [
    port: String.to_integer(System.get_env("HUBCRM_PORT") || "4001"),
    transport_options: [socket_opts: [:inet6]]
  ]

database_url =
  System.get_env("HUBCRM_DATABASE_URL") ||
    raise """
    environment variable DATABASE_URL is missing.
    For example: ecto://USER:PASS@HOST/DATABASE
    """

secret_key_base =
  System.get_env("HUBCRM_SECRET_KEY_BASE") ||
    raise """
    environment variable HUBCRM_SECRET_KEY_BASE is missing.
    You can generate one by calling: mix phx.gen.secret
    """

config :hub_crm, HubCrmWeb.Endpoint, secret_key_base: secret_key_base

config :hub_crm, HubCrm.Repo,
  url: database_url,
  pool_size: String.to_integer(System.get_env("HUBCRM_REPO_POOL_SIZE") || "10")
